version: '3'

services:
  app1:
    build:
      context: ./gloupper
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  app2:
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
